# Generated by Django 4.2.5 on 2025-05-09 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='public',
            field=models.CharField(max_length=15),
        ),
    ]
