# Generated by Django 4.2.5 on 2025-05-12 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0004_alter_userprofile_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='mainImage',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
