# Generated by Django 4.2.5 on 2025-05-12 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0007_alter_article_mainimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='mainImage',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
