# Generated by Django 4.2.5 on 2025-05-15 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0009_article_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='description',
            field=models.TextField(),
        ),
    ]
