# Generated by Django 4.2.5 on 2025-05-28 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0010_alter_article_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='public_since',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
