# Generated by Django 6.0.1 on 2026-03-29 14:44

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0011_article_public_since'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='public',
            field=models.CharField(choices=[('Público', 'Público'), ('Privado', 'Privado'), ('Em Revisão', 'Em Revisão')], default='Em Revisão', max_length=15),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
